### ISSUE TITLE
Fonte CBHPM

### ISSUE THREAD

**Issue by mguilhermetavares** [abinoam/cbhpm_table#3]
Opa, tudo bom?

Vi que você criou um parser de CBHPM pra ruby.

Gostaria de saber onde você conseguiu os dados em xls. Pois já procurei muito, inclusive na ABM e não encontro versão em XLS.

se puder me ajudar, fico agradecido o/

**Comment by abinoam** [comment]
Caro @mguilhermetavares, os dados não são livres infelizmente.
Eles são comprados diretamente na AMB em https://amb.org.br/adquirir-cbhpm/
Eu precisei comprar para não ficar vulnerável a um processo futuro.
Acho isso um tanto absurdo, mas é assim que funciona.

**Comment by mguilhermetavares** [comment]
putz...
@abinoam muito obrigado pela informação. Vou providenciar a compra dos dados. o/
